export const getProduct = [
  {
    categories: "Chairs",
    images: require("./img/Chairs/Chairs1.webp"),
    name: "Students not sitting still? Could their seating be uncomfortable",
    description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution",
    id: 1,
    price: 130,
    review: 99,
    color: ["#807B75", "#404041", "#61AE9C", "#000"],
    imgList: [
      { id:124, imag: require("./img/Chairs/Chairs1.webp") },
      { id:123, imag: require("./img/Chairs/Chairs_1.webp") },
      { id:124, imag: require("./img/Chairs/Chairs_1_2.webp") },
      { id:125, imag: require("./img/Chairs/Chairs_1_3.webp") },
    ],
  },
  {
    categories: "Chairs",
    images: require("./img/Chairs/Chairs2.webp"),
    name: "Garden Chairs 2 pcs with Dark Grey Cushions Solid Teak Wood",
    description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution",
    id: 2,
    price: 70,
    review: 99,
    color: ["#807B75", "#404041", "#61AE9C", "#000"],
    imgList: [
      { id:126, imag: require("./img/Chairs/Chairs2.webp") },
      { id:127, imag: require("./img/Chairs/Chairs_2_1.webp") },
      { id:128, imag: require("./img/Chairs/Chairs_2_2.jpg") },
      { id:129, imag: require("./img/Chairs/Chairs2_3.webp") },
    ],
  },
  {
    categories: "Chairs",
    images: require("./img/Chairs/Chairs3.webp"),
    name: "Wolf Hollow Wood Dining Chairs With Wooden Dining Room Chairs",
    description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution",
    id: 3,
    price: 90,
    review: 99,
    color: ["#807B75", "#404041", "#61AE9C"],
    imgList: [
      {  id:130, imag: require("./img/Chairs/Chairs3.webp") },
      {  id:131, imag: require("./img/Chairs/Chairs3_1.jpg") },
      {  id:132, imag: require("./img/Chairs/Chairs_3_2.jpg") },
      {  id:133, imag: require("./img/Chairs/Chairs_3_3.png") },
      {  id:134, imag: require("./img/Chairs/Chairs_3_4.png") },
    ],
  },
  {
    categories: "Chairs",
    images: require("./img/Chairs/Chairs4.webp"),
    name: "Unit 9 Baamboozle - Baamboozle The Most Fun Classroom Games",
    description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution",
    id: 4,
    price: 50,
    review: 99,
    color: ["#807B75", "#404041", "#61AE9C"],
    imgList: [
      { id:135, imag: require("./img/Chairs/Chairs4.webp") },
      { id:136, imag: require("./img/Chairs/Chairs_4_1.webp") },
      { id:137, imag: require("./img/Chairs/Chairs_4_2.jpg") },
      { id:138, imag: require("./img/Chairs/Chairs_4_3.webp") },
    ],
  },
  {
    categories: "Tables",
    images: require("./img/Tables/Tables1.webp"),
    name: "Siam Круглый латунный стол Sicis",
    description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution",
    id: 5,
    price: 80,
    review: 99,
    color: ["#807B75", "#404041", "#61AE9C", "#000"],
    imgList: [
      { id:139, imag: require("./img//Tables/Tables1.webp") },
      { id:140, imag: require("./img/Tables/Tables_1_1.png") },
      { id:141, imag: require("./img/Tables/Tables_1_2.jpg") },
      { id:142, imag: require("./img/Tables/Tables_1_3.webp") },
    ],
  },
  {
    categories: "Tables",
    images: require("./img/Tables/Tables2.jpg"),
    name: "Expanding table! Dining table, Expandable dining room table",
    description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution",
    id: 6,
    price: 75.00,
    review: 99,
    color: ["#807B75", "#404041", "#61AE9C"],
    imgList: [
      { id:143, imag: require("./img/Tables/Tables2.jpg") },
      { id:144, imag: require("./img/Tables/Tables_2_1.webp") },
      { id:145, imag: require("./img/Tables/Tables_2_2.jpg") },
      { id:146, imag: require("./img/Tables/Tables_2_3.webp") },
    ],
  },
  {
    categories: "Tables",
    images: require("./img/Tables/Tables3.webp"),
    name: "Wooden Dining Tables Archives Esstisch bank, Ovaler küchentisch",
    description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution",
    id: 7,
    price: 70,
    review: 99,
    color: ["#807B75", "#404041", "#61AE9C", "#000"],
    imgList: [
      { id:147, imag: require("./img/Tables/Tables3.webp") },
      { id:148, imag: require("./img/Tables/Tables_3_1.webp") },
      { id:149, imag: require("./img/Tables/Tables_3_2.webp") },
      { id:150, imag: require("./img/Tables/Tables_3_3.webp") },
    ],
  },
  {
    categories: "Tables",
    images: require("./img/Tables/Tables4.webp"),
    name: "IN THE HOUSE Baamboozle - Baamboozle The Most Fun",
    description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution",
    id: 8,
    price: 100,
    review: 99,
    color: ["#807B75", "#404041", "#61AE9C"],
    imgList: [
      {  id:151, imag: require("./img/Chairs/Chairs4.webp") },
      {  id:152, imag: require("./img/Tables/Tables_4_1.webp") },
      {  id:153, imag: require("./img/Tables/Tables_4_2.jpg") },
      {  id:154, imag: require("./img/Tables/Tables_4_3.jpg") },
    ],
  },
  {
    categories: "Sofas",
    images: require("./img/Sofas/Sofas1.webp"),
    name: "Modern Living Rooms With Brown Leather Sofa - Top Dreamer",
    description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution",
    id: 9,
    price: 112,
    review: 99,
    color: ["#807B75", "#404041", "#61AE9C"],
    imgList: [
      {  id:155, imag: require("./img/Sofas/Sofas1.webp") },
      {  id:156, imag: require("./img/Sofas/Sofas_1_1.webp") },
      {  id:157, imag: require("./img/Sofas/Sofas_1_2.jpg") },
      {  id:158, imag: require("./img/Sofas/Sofas_1_3.webp") },
    ],
  },
  {
    categories: "Sofas",
    images: require("./img/Sofas/Sofas2.webp"),
    name: "Granite Flooring 497",
    description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution",
    id: 10,
    price: 190,
    review: 99,
    color: ["#807B75", "#404041", "#61AE9C"],
    imgList: [
      {  id:159, imag: require("./img/Sofas/Sofas2.webp") },
      {  id:160, imag: require("./img/Sofas/Sofas_2_1.webp") },
      {  id:161, imag: require("./img/Sofas/Sofas_2_2.webp") },
    ],
  },
  {
    categories: "Sofas",
    images: require("./img/Sofas/Sofas3.webp"),
    name: "IN THE HOUSE Baamboozle - Baamboozle The Most Fun",
    description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution",
    id: 11,
    price: 90,
    review: 99,
    color: ["#807B75", "#404041", "#61AE9C"],
    imgList: [
      { id:162, imag: require("./img/Sofas/Sofas3.webp") },
      { id:163, imag: require("./img/Sofas/Sofas_3_1.jpg") },
      { id:164, imag: require("./img/Sofas/Sofas_3_2.jpg") },
      { id:165, imag: require("./img/Sofas/Sofas_3_3.jpg") },
    ],
  },
  {
    categories: "Sofas",
    images: require("./img/Sofas/Sofas4.webp"),
    name: "Buy Alpine Sectional Sofa in New Jersey Nordholtz",
    description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution",
    id: 12,
    price: 200,
    review: 99,
    color: ["#807B75", "#404041", "#61AE9C"],
    imgList: [
      { id:166, imag: require("./img/Sofas/Sofas4.webp") },
      { id:167, imag: require("./img/Sofas/Sofas_4_1.webp") },
      { id:168, imag: require("./img/Sofas/Sofas_4_2.webp") },
    ],
  },
  {
    categories: "Lamps",
    images: require("./img/Lamps/Lamps1.webp"),
    name: "American Country Retro Adjustable Table Lamp Simple",
    description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution",
    id: 13,
    price: 120,
    review: 99,
    color: ["#807B75", "#404041", "#61AE9C"],
    imgList: [
      { id:169, imag: require("./img/Lamps/Lamps1.webp") },
      { id:170, imag: require("./img/Lamps/Lamps_1_1.jpg") },
      { id:171, imag: require("./img/Lamps/Lamps_1_2.webp") },
    ],
  },
  {
    categories: "Lamps",
    images: require("./img/Lamps/Lamps2.jpg"),
    name: "Tools & Home Improvement Lamps, Bases & Shades",
    description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution",
    id: 14,
    price: 200,
    review: 99,
    color: ["#807B75", "#404041", "#61AE9C"],
    imgList: [
      { id:172, imag: require("./img/Lamps/Lamps2.jpg") },
      { id:173, imag: require("./img/Lamps/Lamps_2_1.jpg") },
      { id:174, imag: require("./img/Lamps/Lamps_2_2.jpg") },
    ],
  },
  {
    categories: "Lamps",
    images: require("./img/Lamps/Lamps3.jpg"),
    name: "Bangladesh rival please confirm best bright floor lamps evaluate",
    description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution",
    id: 15,
    price: 100,
    review: 99,
    color: ["#807B75", "#404041", "#61AE9C"],
    imgList: [
      { id:175, imag: require("./img/Lamps/Lamps3.jpg") },
      { id:176, imag: require("./img/Lamps/Lamps_3_1.jpg") },
      { id:177, imag: require("./img/Lamps/Lamps_3_2.webp") },
    ],
  },
  {
    categories: "Lamps",
    images: require("./img/Lamps/Lamps4.webp"),
    name: "Buy Alpine Sectional Sofa in New Jersey Nordholtz",
    description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution",
    id: 16,
    price: 120,
    review: 99,
    color: ["#807B75", "#404041", "#61AE9C"],
    imgList: [
      { id:178, imag: require("./img/Lamps/Lamps4.webp") },
      { id:179, imag: require("./img/Lamps/Lamps_4_1.webp") },
      { id:180, imag: require("./img/Lamps/Lamps_4_2.webp") },
    ],
  },
  {
    categories: "Pendants",
    images: require("./img/Pendants/Pendants1.webp"),
    name: "Yongze Choker Gold Chains Galaxy Star Lovely Silver Chain",
    description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution",
    id: 17,
    price: 60,
    review: 99,
    color: ["#807B75", "#404041", "#61AE9C"],
    imgList: [
      { id:181, imag: require("./img/Pendants/Pendants1.webp") },
      { id:182, imag: require("./img/Pendants/Pendants_1_1.webp") },
      { id:183, imag: require("./img/Pendants/Pendants_1_2.webp") },
    ],
  },
  {
    categories: "Pendants",
    images: require("./img/Pendants/Pendants2.webp"),
    name: "Buy Alpine Sectional Sofa in New Jersey Nordholtz",
    description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution",
    id: 18,
    price: 40,
    review: 99,
    color: ["#807B75", "#404041", "#61AE9C"],
    imgList: [
      { id:184, imag: require("./img/Pendants/Pendants2.webp") },
      { id:185, imag: require("./img/Pendants/Pendants_2_1.webp") },
      { id:186, imag: require("./img/Pendants/Pendants_2_2.jpg") },
    ],
  },
  {
    categories: "Pendants",
    images: require("./img/Pendants/Pendants3.webp"),
    name: "Sale pendant heart gold is stock",
    description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution",
    id: 19,
    price: 90,
    review: 99,
    color: ["#807B75", "#404041", "#61AE9C"],
    imgList: [
      { id:187, imag: require("./img/Pendants/Pendants3.webp") },
      { id:188, imag: require("./img/Pendants/Pendants_3_1.jpg") },
      { id:189, imag: require("./img/Pendants/Pendants_3_2.webp") },
    ],
  },
  {
    categories: "Pendants",
    images: require("./img/Pendants/Pendants4.webp"),
    name: "Buy Alpine Sectional Sofa in New Jersey Nordholtz",
    description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution",
    id: 20,
    price: 120,
    review: 99,
    color: ["#807B75", "#404041", "#61AE9C"],
    imgList: [
      { id:190, imag: require("./img/Pendants/Pendants4.webp") },
      { id:191, imag: require("./img/Pendants/Pendants_4_1.webp") },
      { id:192, imag: require("./img/Pendants/Pendants_4_2.png") },
    ],
  },

];
