export const ProductData = [
  {
    id: 11,
    images: require("./imges/1.png"),
    name: "L Shaped Sofa Designs For Small",
    description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of",
    price: 120,
    review: 99,
    color: ["#807B75", "#404041", "#61AE9C", "#000"],
  },
  {
    id: 21,
    images: require("./imges/2.png"),
    name: "App-Assisted Methods to Get the Most Out of Your 24 Hours",
    description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of",
    price: 120,
    review: 99,
    color: ["#807B75", "#404041", "#61AE9C", "#000"],
  },
  {
    id: 31,
    images: require("./imges/3.png"),
    name: " lamps era original design creative table lamp",
    description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of",
    price: 120,
    review: 99,
    color: ["#807B75", "#404041", "#61AE9C", "#000"],
  },
  {
    id: 41,
    images: require("./imges/4.png"),
    name: "Vertically Folding Chairs : folding chairs",
    description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of",
    price: 120,
    review: 99,
    color: ["#807B75", "#404041", "#61AE9C", "#000"],
  },
  {
    id: 51,
    images: require("./imges/x3.webp"),
    name: "Velvet 9162S Costantini Pietro",
    description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of",
    price: 120,
    review: 99,
    color: ["#807B75", "#404041", "#61AE9C", "#000"],
  },
  {
    id: 61,
    images: require("./imges/x2.jpg"),
    name: "Vertically Folding ",
    description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of",
    price: 120,
    review: 99,
    color: ["#807B75", "#404041", "#61AE9C", "#000"],
  },
  {
    id: 711,
    images: require("./imges/x1.webp"),
    name: "Velvet 9162S Costantini Pietro",
    description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of",
    price: 120,
    review: 99,
    color: ["#807B75", "#404041", "#61AE9C", "#000"],
  },
  {
    id: 811,
    images: require("./imges/t.webp"),
    name: "Expanding table! Dining table, Expandable dining room table,",
    description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of",
    price: 120,
    review: 99,
    color: ["#807B75", "#404041", "#61AE9C", "#000"],
  },
  {
    id: 911,
    images: require("./imges/t1.webp"),
    name: " Expandable dining room table",
    description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of",
    price: 120,
    review: 99,
    color: ["#807B75", "#404041", "#61AE9C", "#000"],
  },
  {
    id: 101,
    images: require("./imges/l.webp"),
    name: "Moroccan lamps era original design creative table lamp",
    description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of",
    price: 120,
    review: 99,
    color: ["#807B75", "#404041", "#61AE9C", "#000"],
  },
];
